### Feature engineering for model training

In [32]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from pathlib import Path
import os

In [33]:
# Data loading
raw_data_path= Path.cwd().parent/ "data" / "raw"
file_path = os.path.join(raw_data_path, "sensor_point_dataset_raw.csv")
df = pd.read_csv(file_path)
df.head(10)

,scenario_id,timestep,node_a_pressure,velocity_a,tke_a,tdr_a,wall_shear_a,tailings_vof_a,node_b_pressure,velocity_b,...,pressure_drop_ac,pressure_gradient_ratio,dp_dt_a,dp_dt_b,dp_dt_c,velocity_drop_ab,velocity_drop_bc,tke_drop_ab,tke_drop_bc,flow_velocity
0,blockage_25_loc16m,1,35793.499725,2.534141,0.034635,24.489446,11.197253,0.401012,19965.653843,2.474028,...,31403.077800,1.016219,0.000000,0.000000,0.000000,0.060113,-0.052493,-0.001492,-0.001854,2.474028
1,blockage_25_loc16m,2,36620.208522,2.484805,0.038275,25.658411,10.641124,0.405089,20589.416498,2.421521,...,32025.487923,1.002257,1653.417594,1247.525311,408.597347,0.063284,-0.089215,0.005690,-0.005282,2.421521
2,blockage_25_loc16m,3,36251.794105,2.473708,0.034279,25.294662,9.484428,0.398871,20946.810911,2.531422,...,32432.519693,0.893589,-736.828834,714.788826,-1550.892373,-0.057714,0.128389,-0.003798,0.003425,2.531422
3,blockage_25_loc16m,4,35694.151655,2.478258,0.032199,27.022206,9.489620,0.393614,19637.008191,2.406712,...,31795.602655,1.020249,-1115.284899,-2619.605441,158.549176,0.071546,-0.106356,-0.005860,0.004303,2.406712
4,blockage_25_loc16m,5,35834.383052,2.467021,0.037261,22.894842,10.660725,0.400522,19776.413014,2.442424,...,32793.646002,0.959505,280.462794,278.809648,-1715.623898,0.024597,-0.074601,0.002711,-0.003408,2.442424
5,blockage_25_loc16m,6,36787.297566,2.569537,0.035647,23.439768,10.250242,0.398309,19106.601335,2.521981,...,33068.072143,1.149039,1905.829027,-1339.623359,1356.976745,0.047556,-0.090364,0.000004,-0.002247,2.521981
6,blockage_25_loc16m,7,36144.736489,2.485088,0.034797,24.908137,10.644589,0.395470,20094.551930,2.449309,...,31567.301126,1.034354,-1285.122155,1975.901189,1716.419880,0.035779,-0.003084,-0.004033,0.002115,2.449309
7,blockage_25_loc16m,8,35566.008814,2.496601,0.034091,24.837599,10.843902,0.395164,19447.852780,2.483421,...,32307.184967,0.995622,-1157.455349,-1293.398300,-2637.223031,0.013180,-0.015963,-0.000884,-0.004864,2.483421
8,blockage_25_loc16m,9,36058.571722,2.555000,0.033721,24.339944,9.959091,0.393493,20766.372402,2.433175,...,32211.013981,0.903858,985.125815,2637.039245,1177.467786,0.121826,0.000501,0.004045,-0.005438,2.433175
9,blockage_25_loc16m,10,36087.612877,2.511439,0.037675,25.088742,10.973236,0.402177,19771.627334,2.479944,...,31701.560308,1.060473,58.082310,-1989.490136,1076.989657,0.031495,-0.060091,0.004455,0.001433,2.479944

In [34]:
df.shape

(31500, 35)

- We have no data point that is duplicated.

In [35]:
# Data quality
print(f"The shape of the dataframe is {df.shape}")
print(f"There are {df.shape[0]} rows and {df.shape[1]} columns")

The shape of the dataframe is (31500, 35)
There are 31500 rows and 35 columns

In [36]:
df.dtypes

scenario_id                    str
timestep                     int64
node_a_pressure            float64
velocity_a                 float64
tke_a                      float64
tdr_a                      float64
wall_shear_a               float64
tailings_vof_a             float64
node_b_pressure            float64
velocity_b                 float64
tke_b                      float64
tdr_b                      float64
wall_shear_b               float64
tailings_vof_b             float64
node_c_pressure            float64
velocity_c                 float64
tke_c                      float64
tdr_c                      float64
wall_shear_c               float64
tailings_vof_c             float64
label                        int64
effect_factor              float64
fault_type                     str
pressure_drop_ab           float64
pressure_drop_bc           float64
pressure_drop_ac           float64
pressure_gradient_ratio    float64
dp_dt_a                    float64
dp_dt_b                    float64
dp_dt_c                    float64
velocity_drop_ab           float64
velocity_drop_bc           float64
tke_drop_ab                float64
tke_drop_bc                float64
flow_velocity              float64
dtype: object

### Sort for Temporal Differences

In [37]:
df = df.sort_values(by = ["scenario_id", "timestep"], ascending=[True, True])
# Reset index after sorting
df = df.reset_index(drop=True)

# verification step: check ordering for one scenario
sample_id = df["scenario_id"].iloc[0]
print("Checking scenario:", sample_id)
# Check for the first 10 rows of this scenario
df.head(10)

Checking scenario: blockage_25_loc16m

,scenario_id,timestep,node_a_pressure,velocity_a,tke_a,tdr_a,wall_shear_a,tailings_vof_a,node_b_pressure,velocity_b,...,pressure_drop_ac,pressure_gradient_ratio,dp_dt_a,dp_dt_b,dp_dt_c,velocity_drop_ab,velocity_drop_bc,tke_drop_ab,tke_drop_bc,flow_velocity
0,blockage_25_loc16m,1,35793.499725,2.534141,0.034635,24.489446,11.197253,0.401012,19965.653843,2.474028,...,31403.077800,1.016219,0.000000,0.000000,0.000000,0.060113,-0.052493,-0.001492,-0.001854,2.474028
1,blockage_25_loc16m,2,36620.208522,2.484805,0.038275,25.658411,10.641124,0.405089,20589.416498,2.421521,...,32025.487923,1.002257,1653.417594,1247.525311,408.597347,0.063284,-0.089215,0.005690,-0.005282,2.421521
2,blockage_25_loc16m,3,36251.794105,2.473708,0.034279,25.294662,9.484428,0.398871,20946.810911,2.531422,...,32432.519693,0.893589,-736.828834,714.788826,-1550.892373,-0.057714,0.128389,-0.003798,0.003425,2.531422
3,blockage_25_loc16m,4,35694.151655,2.478258,0.032199,27.022206,9.489620,0.393614,19637.008191,2.406712,...,31795.602655,1.020249,-1115.284899,-2619.605441,158.549176,0.071546,-0.106356,-0.005860,0.004303,2.406712
4,blockage_25_loc16m,5,35834.383052,2.467021,0.037261,22.894842,10.660725,0.400522,19776.413014,2.442424,...,32793.646002,0.959505,280.462794,278.809648,-1715.623898,0.024597,-0.074601,0.002711,-0.003408,2.442424
5,blockage_25_loc16m,6,36787.297566,2.569537,0.035647,23.439768,10.250242,0.398309,19106.601335,2.521981,...,33068.072143,1.149039,1905.829027,-1339.623359,1356.976745,0.047556,-0.090364,0.000004,-0.002247,2.521981
6,blockage_25_loc16m,7,36144.736489,2.485088,0.034797,24.908137,10.644589,0.395470,20094.551930,2.449309,...,31567.301126,1.034354,-1285.122155,1975.901189,1716.419880,0.035779,-0.003084,-0.004033,0.002115,2.449309
7,blockage_25_loc16m,8,35566.008814,2.496601,0.034091,24.837599,10.843902,0.395164,19447.852780,2.483421,...,32307.184967,0.995622,-1157.455349,-1293.398300,-2637.223031,0.013180,-0.015963,-0.000884,-0.004864,2.483421
8,blockage_25_loc16m,9,36058.571722,2.555000,0.033721,24.339944,9.959091,0.393493,20766.372402,2.433175,...,32211.013981,0.903858,985.125815,2637.039245,1177.467786,0.121826,0.000501,0.004045,-0.005438,2.433175
9,blockage_25_loc16m,10,36087.612877,2.511439,0.037675,25.088742,10.973236,0.402177,19771.627334,2.479944,...,31701.560308,1.060473,58.082310,-1989.490136,1076.989657,0.031495,-0.060091,0.004455,0.001433,2.479944

###  Pressure Features

In [38]:
def engineer_pressure_features(df, scenario_col="label", dt=0.5, epsilon=1e-8):

    df = df.sort_values([scenario_col, "timestep"]).copy()

    # spatial gradients
    df["pressure_drop_ab"] = df["node_a_pressure"] - df["node_b_pressure"]
    df["pressure_drop_bc"] = df["node_b_pressure"] - df["node_c_pressure"]
    df["pressure_drop_ac"] = df["node_a_pressure"] - df["node_c_pressure"]

    df["pressure_gradient_ab"] = df["pressure_drop_ab"] / 20.0
    df["pressure_gradient_bc"] = df["pressure_drop_bc"] / 20.0
    df["pressure_gradient_ac"] = df["pressure_drop_ac"] / 40.0

    # midpoint analysis
    """
    positive = blockage (pressure spike at B)
    negative = leak (pressure drop at B)
    """
    df["expected_midpoint_pressure"] = (df["node_a_pressure"] + df["node_c_pressure"])/2
    df["midpoint_deviation"] = df["node_b_pressure"] - df["expected_midpoint_pressure"]

    # Pressure asymmetry
    df["pressure_asynnetry"] = abs(df["pressure_drop_ab"] -  df["pressure_drop_bc"])

    # Normalized pressure tactics
    df["pressure_ratio_ab"] = df["node_a_pressure"] / (df["node_b_pressure"] + epsilon)
    df["pressure_ratio_bc"] = df["node_b_pressure"] / (df["node_c_pressure"] + epsilon)
    df["pressure_ratio_ac"] = df["node_a_pressure"] / (df["node_c_pressure"] + epsilon)

    # temporal rates (per scenario)



    return df

###  Velocity Features

In [39]:
def engineer_velocity_features(df):

    df['velocity_drop_ab'] = df['velocity_a'] - df['velocity_b']
    df['velocity_drop_bc'] = df['velocity_b'] - df['velocity_c']
    df['velocity_drop_ac'] = df['velocity_a'] - df['velocity_c']

    df['mean_velocity'] = df[['velocity_a', 'velocity_b', 'velocity_c']].mean(axis=1)

    df['velocity_deviation_a'] = df['velocity_a'] - df['mean_velocity']
    df['velocity_deviation_b'] = df['velocity_b'] - df['mean_velocity']
    df['velocity_deviation_c'] = df['velocity_c'] - df['mean_velocity']

    # for each scenario group sorted by timestep:
    df = df.sort_values(['label', 'timestep']).copy()

    df['dv_dt_a'] = df.groupby('label')['velocity_a'].diff() / 0.5
    df['dv_dt_b'] = df.groupby('label')['velocity_b'].diff() / 0.5
    df['dv_dt_c'] = df.groupby('label')['velocity_c'].diff() / 0.5

    df[['dv_dt_a', 'dv_dt_b', 'dv_dt_c']] = df[['dv_dt_a', 'dv_dt_b', 'dv_dt_c']].fillna(0)

    return df

### Turbulence Features